# Generated by Django 2.2.9 on 2020-02-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='size',
        ),
        migrations.AddField(
            model_name='table',
            name='m',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='n',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
