# Generated by Django 2.2.9 on 2020-02-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_table_cells'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_cells',
            name='m',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table_cells',
            name='n',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table_cells',
            name='table',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Table'),
            preserve_default=False,
        ),
    ]
