# Generated by Django 2.2.9 on 2020-02-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200220_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='cell',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
