# Generated by Django 2.2.9 on 2020-02-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200222_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='cell',
        ),
    ]
