# Generated by Django 2.2.9 on 2020-02-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
