# Generated by Django 2.2.9 on 2020-02-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
